services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  app:
    build: .
    container_name: urlshortener_app
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "${PORT}:${PORT}"
    environment:
      PGUSER: ${DB_USER}
      PGHOST: ${DB_HOST}
      PGDATABASE: ${DB_NAME}
      PGPASSWORD: ${DB_PASSWORD}
      PGPORT: ${DB_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - .:/usr/src/app
    command: ["node", "index.js"]

volumes:
  pgdata:
