openapi: 3.0.0
info:
  title: URL Shortener API
  description: API for creating and managing short URLs with simple analytics
  version: 1.0.0
servers:
  - url: https://dummyurlshortener.duckdns.org/
    description: Production server
  - url: http://localhost:3000/
    description: Local development server

components:
  securitySchemes:
    GoogleOAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            email: "User email"
            profile: "User profile"
  schemas:
    ShortUrlResponse:
      type: object
      properties:
        shortUrl:
          type: string
          example: "https://short.url/abc123"
        createdAt:
          type: string
          format: date-time
          example: "2025-02-05T12:34:56Z"

    AnalyticsResponse:
      type: object
      properties:
        totalClicks:
          type: integer
          example: 150
        uniqueUsers:
          type: integer
          example: 100
        clicksByDate:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date
                example: "2023-10-05"
              count:
                type: integer
                example: 25
        osType:
          type: array
          items:
            type: object
            properties:
              osName:
                type: string
                example: "Windows"
              uniqueClicks:
                type: integer
                example: 50
              uniqueUsers:
                type: integer
                example: 35
        deviceType:
          type: array
          items:
            type: object
            properties:
              deviceName:
                type: string
                example: "Mobile"
              uniqueClicks:
                type: integer
                example: 80
              uniqueUsers:
                type: integer
                example: 60

paths:
  /auth/google:
    get:
      tags: [Authentication]
      summary: Initiate Google OAuth flow
      responses:
        "302":
          description: Redirect to Google OAuth consent screen

  /auth/google/callback:
    get:
      tags: [Authentication]
      summary: Google OAuth callback
      responses:
        "200":
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

  /api/url/shorten:
    post:
      tags: [URL Management]
      summary: Create a short URL
      security:
        - GoogleOAuth: [email, profile]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                longUrl:
                  type: string
                  format: uri
                  example: "https://example.com/very-long-url"
                customAlias:
                  type: string
                  example: "my-alias"
                topic:
                  type: string
                  example: "acquisition"
      responses:
        "201":
          description: Short URL created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ShortUrlResponse"
        "429":
          description: Rate limit exceeded

  /api/url/shorten/{alias}:
    get:
      tags: [Redirection]
      summary: Redirect to original URL
      parameters:
        - name: alias
          in: path
          required: true
          schema:
            type: string
      responses:
        "302":
          description: Redirect to original URL
        "404":
          description: URL not found

  /api/analytics/{alias}:
    get:
      tags: [Analytics]
      summary: Get analytics for a specific short URL
      security:
        - GoogleOAuth: [email, profile]
      parameters:
        - name: alias
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Analytics data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnalyticsResponse"

  /api/analytics/topic/{topic}:
    get:
      tags: [Analytics]
      summary: Get analytics for a topic
      security:
        - GoogleOAuth: [email, profile]
      parameters:
        - name: topic
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Topic analytics
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalClicks:
                    type: integer
                    example: 500
                  uniqueUsers:
                    type: integer
                    example: 300
                  clicksByDate:
                    type: array
                    items:
                      $ref: "#/components/schemas/AnalyticsResponse/properties/clicksByDate/items"
                  urls:
                    type: array
                    items:
                      type: object
                      properties:
                        shortUrl:
                          type: string
                        totalClicks:
                          type: integer
                        uniqueUsers:
                          type: integer

  /api/analytics/overall:
    get:
      tags: [Analytics]
      summary: Get overall analytics
      security:
        - GoogleOAuth: [email, profile]
      responses:
        "200":
          description: Overall analytics
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalUrls:
                    type: integer
                    example: 10
                  totalClicks:
                    type: integer
                    example: 1500
                  uniqueUsers:
                    type: integer
                    example: 1000
                  clicksByDate:
                    $ref: "#/components/schemas/AnalyticsResponse/properties/clicksByDate"
                  osType:
                    $ref: "#/components/schemas/AnalyticsResponse/properties/osType"
                  deviceType:
                    $ref: "#/components/schemas/AnalyticsResponse/properties/deviceType"
